### ISSUE TITLE
Grammar error "Search for a City"

### ISSUE THREAD

**Issue by ghost** [Love-Ivy/ILW6Weather#6]
Hey buddy, "City" shouldn't be capitalized since it's not a proper noun in this usage.

**Comment by HeartSleeves** [comment]
We have taken your comment into consideration. Upon further review, we have determined the element to be a subdominant element worthy of using the Title Case. For this reason, your input shall be rejected.

**Comment by ghost** [comment]
So Laaaaaaaaaaaaame
________________________________
